# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Qualys
version:      0.02
version_from: Qualys.pm
installdirs:  site
requires:
    HTTP::Request:                 0
    LWP::UserAgent:                2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
